EndOfSemester/ASM_TeamVit/Pizza_TeamVit-master/Pizza_TeamVit/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Pizza_TeamVit.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pizza_TeamVit.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStoreRepository repository;
        public NavigationMenuViewComponent(IStoreRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            return View(repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
        //public string Invoke()
        //{
        //    return "Hello from the Nav View Component";
        //}
    }
}

EndOfSemester/ASM_TeamVit/Pizza_TeamVit-master/Pizza_TeamVit/Views/Shared/ProductSummary.cshtml
@model Product 
<div class="card card-outline-primary m-1 p-1 text-center" style="width:30%;float:left; height: 530px">
    <div class="bg-faded p-1">
        <img src="@Model.Img" class="text-center" height="270" width="270" style="text-align:center"/>
        <h4 class="text-center">
            @Model.Name<br/>
        </h4>
    </div>

    <form method="post" asp-page="/Cart" id="@Model.ProductId">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <div class="mt-3 text-center" style="height:50px;">
            <span class="card-text p-2">
                @Model.Description<br />
            </span>
        </div>

        <div class="mt-3">
            <span class="badge badge-pill badge-primary p-2" style="font-weight:bold; font-size:16px; line-height:1.5;">@Model.Price.ToString("c")</span>
        </div>

        <div class="mt-3">
            <button type="submit" class="btn btn-success btn-sm p-2">
                Add To Cart
            </button>
        </div>

    </form>
</div>

EndOfSemester/ASM_TeamVit/Pizza_TeamVit-master/Pizza_TeamVit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza_TeamVit</title>
    <link rel="stylesheet" href="~/css//site.css" />
    <link rel="stylesheet" href="/lib/twitter-bootstrap/css/bootstrap.min.css" />
</head>
<body>

    <div class="bg-info text-white p-2">
        <span class="navbar-brand ml-2">
            <b>Pizza_TeamVit</b>
        </span>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            @*Put something useful here later*@
            <vc:navigation-menu />
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>